import Head from 'next/head'
import Navbar from '../components/Navbar'
import Hero from '../components/Homepage/Hero'
import { useEffect, useState } from 'react';

export default function Home() {
  const [colorChange, setColorchange] = useState(false);
  const changeNavbarColor = () => {
    if (window.scrollY >= 80) {
      setColorchange(true);
    } else {
      setColorchange(false);
    }
  };
  useEffect(() => {
    window.addEventListener("scroll", changeNavbarColor);
  }, []);

  return (
    <div>
      <Head>
        <title>Tuffer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {colorChange ? (
        <div className="fixed top-0 w-full bg-white shadow z-[999]">
          <Navbar />
        </div>
      ) : (
        <div className="fixed top-0 w-full z-[999]">
          <Navbar />
        </div>
      )}
      <Hero />
    </div>
  )
}
